### ISSUE TITLE
Please consider renaming the executeable to pypi-search (like the package)

### ISSUE THREAD

**Issue by inktrap** [asadmoosvi/pypi-search#4]
I installed pypi-search via `pipx` which symlinks executeables to a shared directory which I then append to my `$PATH`.

Since your executeable is named `pypisearch` I can't use  `pypisearch` from the corresponding package (well ofc I could rename either of them, but that would break during updates): https://pypi.org/project/pypisearch/

Please consider renaming the executeable to pypi-search (like the package).

**Comment by asadmoosvi** [comment]
Thank you for pointing that out. The executable is the same name as the package now as of d71f6fb.
